#!/usr/bin/env node
// scripts/build-til.mjs
// til/MMDD/MMDD.md (synced from Notion by sync-til-content.mjs) → src/data/til.ts
//
// til.ts used to be regenerated straight from the Notion database's title
// property (scripts/sync-notion.mjs), independently of which dates actually
// had synced markdown. Two things went wrong because of that:
//   1. Notion rows with a blank/placeholder title (e.g. a bare "@2026년 5월
//      29일" date mention) produced ugly date-only entries in the TIL list.
//   2. Rows with no synced til/<folder> yet (new, or deliberately excluded
//      empty days) still showed up in til.ts, shifting every entry after
//      them out of alignment with the positional til.ts<->til/ folder
//      mapping tilContent.ts used to rely on — surfacing as "원문을 찾을 수
//      없습니다" on unrelated, otherwise-fine entries.
//
// Every synced note already opens with a "# MMDD(Topic).md" heading (that's
// where the user actually writes the date + topic together), so building
// the list straight from disk sidesteps both problems: only dates with real
// synced content ever appear, and each entry carries its own `folder` so
// tilContent.ts can look it up directly instead of guessing by position.
//
// 사용법:
//   node scripts/build-til.mjs
import { writeFile, readdir, readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const TIL_DIR = path.join(ROOT, 'til')
const OUT_PATH = path.join(ROOT, 'src', 'data', 'til.ts')

function parseTitleFromHeading(headingText, fallback) {
  const text = headingText.replace(/^#+\s*/, '').trim()
  const m = text.match(/^\d{3,4}\(([\s\S]+)\)\s*\.?\s*md\s*$/i)
  if (m) return m[1].trim()
  const m2 = text.match(/^\d{3,4}\(([\s\S]+)\)\s*$/)
  if (m2) return m2[1].trim()
  return text || fallback
}

async function main() {
  const folders = (await readdir(TIL_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort() // MMDD[_n] sorts oldest-first within a year

  const entries = []
  for (const folder of folders) {
    const mmdd = folder.split('_')[0]
    if (!/^\d{4}$/.test(mmdd)) continue
    const mdPath = path.join(TIL_DIR, folder, `${folder}.md`)
    let firstLine = ''
    try {
      const raw = await readFile(mdPath, 'utf8')
      firstLine = raw.split('\n').find((line) => line.trim()) ?? ''
    } catch {
      continue // no markdown synced for this folder yet — skip
    }

    const dateLabel = `${mmdd.slice(0, 2)}.${mmdd.slice(2, 4)}`
    const title = parseTitleFromHeading(firstLine, dateLabel)
    entries.push({ folder, title, date: dateLabel })
  }

  entries.reverse() // newest-first, matching the site's display order
  const items = entries.map((e, index) => ({ id: String(index + 1), ...e }))

  const body = items
    .map(
      (it) =>
        `  { id: ${JSON.stringify(it.id)}, title: ${JSON.stringify(it.title)}, date: ${JSON.stringify(it.date)}, folder: ${JSON.stringify(it.folder)} },`
    )
    .join('\n')

  const source = `import type { ClassifiedItem } from './types'

// Auto-generated by scripts/build-til.mjs from til/*/*.md — do not edit by
// hand, changes will be overwritten on the next sync. Each entry's folder
// points at its til/<folder>/<folder>.md source note.
export const tilList: ClassifiedItem[] = [
${body}
]
`

  await writeFile(OUT_PATH, source, 'utf8')
  console.log(`[build-til] Wrote ${items.length} til item(s) to src/data/til.ts`)
}

main().catch((err) => {
  console.error('[build-til] 오류:', err)
  process.exit(1)
})
