// Pulls Tech Logs from its Notion database into src/data/techlogs.ts. Runs
// automatically before `npm run build` (see package.json's "prebuild");
// also runnable directly via `npm run sync:notion`.
//
// TIL used to be synced here too, straight from the Notion database's title
// property. That's now handled by scripts/build-til.mjs instead, which
// builds src/data/til.ts from the already-synced til/*/*.md notes on disk —
// see that script's header comment for why.
//
// Needs NOTION_TOKEN plus one database id per source — see .env.example.
// Missing credentials aren't an error: the script just leaves the existing
// src/data/*.ts files alone, so local dev and forks without Notion access
// keep working off whatever was last committed.
import 'dotenv/config'
import { Client } from '@notionhq/client'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { deriveTitle } from './til-title.mjs'

const dataDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data')

const SOURCES = [
  { key: 'techlogs', envVar: 'NOTION_TECHLOGS_DATABASE_ID', outFile: 'techlogs.ts', exportName: 'techlogsList' },
]

const token = process.env.NOTION_TOKEN
if (!token) {
  console.log('[sync-notion] NOTION_TOKEN not set — keeping src/data/*.ts as-is.')
  process.exit(0)
}

const notion = new Client({ auth: token })

function findProperty(properties, type) {
  return Object.values(properties).find((p) => p.type === type)
}

// Prefer a rich_text property that looks like a daily summary/TIL field
// (by key name); fall back to the first non-empty rich_text property of any
// name, since database column naming isn't guaranteed across sources.
function findSummaryText(properties) {
  const richTextEntries = Object.entries(properties).filter(([, p]) => p.type === 'rich_text')
  const preferred = richTextEntries.find(([key]) => /til|summary|요약/i.test(key))
  const [, prop] = preferred ?? richTextEntries.find(([, p]) => p.rich_text?.length) ?? []
  return prop?.rich_text?.map((t) => t.plain_text).join('') ?? ''
}

function formatDate(iso) {
  const d = new Date(iso)
  return `${String(d.getMonth() + 1).padStart(2, '0')}.${String(d.getDate()).padStart(2, '0')}`
}

async function fetchAllPages(databaseId) {
  // Notion's 2025-09-03+ API moved querying from the database itself to its
  // "data source" (a database can have more than one, but every database
  // created the old way — which is all of them here — has exactly one).
  const database = await notion.databases.retrieve({ database_id: databaseId })
  const dataSourceId = database.data_sources[0]?.id
  if (!dataSourceId) throw new Error(`Database ${databaseId} has no data sources`)

  const pages = []
  let cursor
  do {
    const res = await notion.dataSources.query({
      data_source_id: dataSourceId,
      start_cursor: cursor,
      page_size: 100,
    })
    pages.push(...res.results)
    cursor = res.has_more ? (res.next_cursor ?? undefined) : undefined
  } while (cursor)
  return pages
}

function mapPage(page) {
  const titleProp = findProperty(page.properties, 'title')
  const dateProp = findProperty(page.properties, 'date')
  const titleText = titleProp?.title?.map((t) => t.plain_text).join('').trim() ?? ''
  const isoDate = dateProp?.date?.start ?? ''
  const dateLabel = isoDate ? formatDate(isoDate) : ''
  const title = deriveTitle({
    titleText,
    summaryText: findSummaryText(page.properties),
    fallbackDateLabel: dateLabel || undefined,
  })
  return {
    title,
    date: dateLabel,
    notionUrl: page.url,
    sortKey: isoDate,
  }
}

function toModuleSource(exportName, items) {
  const body = items
    .map(
      (it) =>
        `  { id: ${JSON.stringify(it.id)}, title: ${JSON.stringify(it.title)}, date: ${JSON.stringify(it.date)}, notionUrl: ${JSON.stringify(it.notionUrl)} },`
    )
    .join('\n')
  return `import type { ClassifiedItem } from './types'

// Auto-generated by scripts/sync-notion.mjs from a Notion database — do not
// edit by hand, changes will be overwritten on the next sync. Committed as
// the last-known-good fallback for local dev / forks without NOTION_TOKEN.
export const ${exportName}: ClassifiedItem[] = [
${body}
]
`
}

for (const source of SOURCES) {
  const databaseId = process.env[source.envVar]
  if (!databaseId) {
    console.log(`[sync-notion] ${source.envVar} not set — skipping ${source.key}.`)
    continue
  }

  console.log(`[sync-notion] Fetching ${source.key} from Notion database ${databaseId}...`)
  const pages = await fetchAllPages(databaseId)
  const items = pages
    .map(mapPage)
    .sort((a, b) => (a.sortKey < b.sortKey ? 1 : a.sortKey > b.sortKey ? -1 : 0))
    // Sequential ids (newest-first, "1".."N") instead of raw Notion page ids,
    // so /techlogs/:id routes stay short and stable across re-syncs as long
    // as the underlying Notion rows don't change order.
    .map(({ sortKey, ...item }, index) => ({ id: String(index + 1), ...item }))

  const outPath = path.join(dataDir, source.outFile)
  await writeFile(outPath, toModuleSource(source.exportName, items), 'utf8')
  console.log(`[sync-notion] Wrote ${items.length} ${source.key} item(s) to src/data/${source.outFile}`)
}
